In [14]:
import pandas as pd

In [15]:
data = {"Fruits":["Mango", "graps", "papaya", "banana", "Carrot"],
        "Price":[120,200,141,170,55],
        "quantity":[7,12,8,80,90]}

df1 = pd.DataFrame(data)

In [16]:
df1

   Fruits  Price  quantity
0   Mango    120         7
1   graps    200        12
2  papaya    141         8
3  banana    170        80
4  Carrot     55        90

In [17]:
df2 = pd.DataFrame(data)

df2.loc[0, "Price"] = 135
df2.loc[2, "Price"] = 145
df2.loc[3, "Price"] = 88
df2.loc[4, "Price"] = 72


df2.loc[0, "quantity"] = 15
df2.loc[2, "quantity"] = 14
df2.loc[3, "quantity"] = 81
df2.loc[4, "quantity"] = 45

In [18]:
df2

   Fruits  Price  quantity
0   Mango    135        15
1   graps    200        12
2  papaya    145        14
3  banana     88        81
4  Carrot     72        45