In [15]:
import pandas as pd

In [16]:
data = pd.read_excel("ESD.xlsx")

In [17]:
data

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,E03094,Wesley Young,Sr. Analyst,Marketing,Speciality Products,Male,Caucasian,33,2016-09-18,98427,0.00,United States,Columbus,NaT
996,E01909,Lillian Khan,Analyst,Finance,Speciality Products,Female,Asian,44,2010-05-31,47387,0.00,China,Chengdu,2018-01-08
997,E04398,Oliver Yang,Director,Marketing,Speciality Products,Male,Asian,31,2019-06-10,176710,0.15,United States,Miami,NaT
998,E02521,Lily Nguyen,Sr. Analyst,Finance,Speciality Products,Female,Asian,33,2012-01-28,95960,0.00,China,Chengdu,NaT
999,E03545,Sofia Cheng,Vice President,Accounting,Corporate,Female,Asian,63,2020-07-26,216195,0.31,United States,Miami,NaT

In [18]:
grp = data.groupby("Department").agg({"Gender":"count"})

In [19]:
print(grp)

                 Gender
Department
Accounting           96
Engineering         158
Finance             120
Human Resources     125
IT                  241
Marketing           120
Sales               140

In [20]:
grp = data.groupby(["Department", "Gender"]).agg({"Gender":"count"})

In [21]:
grp

                        Gender
Department      Gender
Accounting      Female      53
                Male        43
Engineering     Female      80
                Male        78
Finance         Female      69
                Male        51
Human Resources Female      64
                Male        61
IT              Female     119
                Male       122
Marketing       Female      57
                Male        63
Sales           Female      76
                Male        64

In [22]:
grp = data.groupby("Country").agg({"Annual Salary":"max"})

In [23]:
grp

               Annual Salary
Country
Brazil                258426
China                 257194
United States         258498

In [24]:
data.head(5)

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT

In [26]:
data.groupby("Department")["Annual Salary"].sum()

Department
Accounting         11822107
Engineering        17227563
Finance            14736347
Human Resources    14757305
IT                 23567499
Marketing          15559564
Sales              15546980
Name: Annual Salary, dtype: int64

In [28]:
data.groupby(["Department", "Gender"])["Annual Salary"].sum()

Department       Gender
Accounting       Female     6914128
                 Male       4907979
Engineering      Female     8377656
                 Male       8849907
Finance          Female     8424540
                 Male       6311807
Human Resources  Female     7693326
                 Male       7063979
IT               Female    11344574
                 Male      12222925
Marketing        Female     7145899
                 Male       8413665
Sales            Female     8278622
                 Male       7268358
Name: Annual Salary, dtype: int64

In [29]:
data.groupby(["Department", "Gender"])["Annual Salary"].count()

Department       Gender
Accounting       Female     53
                 Male       43
Engineering      Female     80
                 Male       78
Finance          Female     69
                 Male       51
Human Resources  Female     64
                 Male       61
IT               Female    119
                 Male      122
Marketing        Female     57
                 Male       63
Sales            Female     76
                 Male       64
Name: Annual Salary, dtype: int64

In [30]:
data.groupby(["Department", "Gender"])["Annual Salary"].agg(["min", "max"])

                          min     max
Department      Gender
Accounting      Female  45049  258426
                Male    50883  252325
Engineering     Female  60017  255431
                Male    60055  254289
Finance         Female  43363  255369
                Male    41336  250767
Human Resources Female  43001  249801
                Male    41728  250953
IT              Female  40124  246589
                Male    40063  256561
Marketing       Female  40897  249270
                Male    40752  257194
Sales           Female  41429  258498
                Male    44732  258081